### ISSUE TITLE
catalog.ini has no entry for glottolog

### ISSUE THREAD

**Issue by tzakharko** [cldf-datasets/autotypcldf#1]
Hi @xrotwang, I am attempting to run this using 

    cldfbench makecldf cldfbench_autotyp.py --glottolog-version v4.5

but getting the error 'Config ~/Library/Application Support/cldf/catalog.ini has no entry for glottolog'.  The glottolog extra is installed. There is no "catalog.ini" in the said directory. In fact, it is empty. 

Is there some extra setup step I have to do first?

**Comment by xrotwang** [comment]
Ah, sorry. Either you create `catalog.ini` running `cldfbench catconfig` (see https://github.com/cldf/cldfbench/#catalogs) or you pass the path explicitly:
```
cldfbench makecldf cldfbench_autotyp.py --glottolog PATH/TO/glottolog --glottolog-version v4.5
```

**Comment by tzakharko** [comment]
Thanks, got it!
